server.port=8083
spring.application.name=accessservice

spring.datasource.url=jdbc:postgresql://localhost:5432/scholarsphere_access
spring.datasource.username=postgres
spring.datasource.password=Deviramdheeraj#2006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/