server.port=8082
spring.application.name=content-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/scholarsphere_cs
spring.datasource.username=postgres
spring.datasource.password=Deviramdheeraj#2006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect